// Code generated by "stringer -type=Leaf"; DO NOT EDIT.

package regx

func _() {
	_ = "STUB: not implemented"
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	return
}

const _Leaf_name = "CMNTDESCDSBLFLIPFQDNHOSTHTTPIPBHLEAFLBRCMISCMLTIMPTYNAMENODERBRCSUFX"

var _Leaf_index = [...]uint8{0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68}

func (i Leaf) String() string { _ = "STUB: not implemented"; return "" }
