// Code generated by "stringer -type=ntype"; DO NOT EDIT.

package edgeos

func _() {
	_ = "STUB: not implemented"
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	return
}

const _ntype_name = "unknowndomnexcDomnexcHostexcRoothostpreDomnpreHostpreRootroot"

var _ntype_index = [...]uint8{0, 7, 11, 18, 25, 32, 36, 43, 50, 57, 61}

func (i ntype) String() string { _ = "STUB: not implemented"; return "" }
